export const PRELOADER_CONFIG = {
    mobile: {
        fontSize: "100px",
        lineHeight: "100px",
        counterRight: "20px",
        counterBottom: "20px",
        loaderHeight: 20,
        loaderWidth: 130,
        bar1Max: 120,
        bar2Max: 80,
        outro: {
            counterY: -60,
            bar1Rotate: 90,
            bar1Y: -23,
            bar2X: -28,
            bar2Y: 27,
            finalScale: 20,
            finalX: 400,
            finalY: 500,
        },
    },
    tablet: {
        fontSize: "160px",
        lineHeight: "160px",
        counterRight: "20px",
        counterBottom: "20px",
        loaderHeight: 30,
        loaderWidth: 180,
        bar1Max: 160,
        bar2Max: 90,
        outro: {
            counterY: -100,
            bar1Rotate: 90,
            bar1Y: -23,
            bar2X: -42,
            bar2Y: 50,
            finalScale: 35,
            finalX: 1200,
            finalY: 300,
        },
    },
    desktop: {
        fontSize: "240px",
        lineHeight: "240px",
        counterRight: "50px",
        counterBottom: "50px",
        loaderHeight: 50,
        loaderWidth: 300,
        bar1Max: 200,
        bar2Max: 100,
        outro: {
            counterY: -120,
            bar1Rotate: 90,
            bar1Y: -50,
            bar2X: -75,
            bar2Y: 75,
            finalScale: 40,
            finalX: 2000,
            finalY: 500,
        },
    },
} as const;

export const PRELOADER_TIMING = {
    loaderBarDuration: 1.2,
    loader2Delay: 0.7,
    revealStart: 2,
    scaleStart: 3.0,
    fadeStart: 3.4,
} as const;
